skiplistmaxheight: 10
btreedegree: 4
memtablecap: 2
memtablecontainer: skiplist
sstableallinone: true
filterprecision: 0.01
summarystep: 5
cachesize: 10
wallowwatermark: 10
walsegmentsize: 2000
tbucketresetduration: 7000
tbucketmaxtokens: 5
lsmmaxlevel: 4
lsmlevelsize: 2
merklechunksize: 100
