skiplistmaxheight: 10
btreedegree: 4
memtablecap: 2
memtablecontainer: btree
sstableallinone: true
filterprecision: 0.01
summarystep: 5
cachesize: 10
wallowwatermark: 10
walsegmentsize: 5
tbucketresetduration: 7000
tbucketmaxtokens: 5
lsmmaxlevel: 4
lsmlevelsize: 4
merklechunksize: 100
