skiplistmaxheight: 10
btreedegree: 4
memtablecap: 2
memtablecontainer: skiplist
sstableallinone: true
filterprecision: 0.01
summarystep: 5
cachesize: 10
wallowwatermark: 10
walsegmentsize: 1048576
tbucketresetduration: 2000
tbucketmaxtokens: 5
lsmmaxlevel: 4
lsmlevelsize: 2
