skiplistmaxheight: 10
btreedegree: 4
memtablecap: 3
memtablecontainer: btree
sstableallinone: true
filterprecision: 0.01
summarystep: 5
cachesize: 4
wallowwatermark: 5
walsegmentsize: 256
tbucketresetduration: 7000
tbucketmaxtokens: 5
lsmmaxlevel: 4
lsmlevelsize: 2
merklechunksize: 100
